platform :ios,"7.0"
target "Cparadise" do

pod 'MJRefresh', '~> 3.1.0'
pod 'MMMaterialDesignSpinner', '~> 0.2.3'
pod 'MJExtension', '~> 3.0.10'
pod 'SDWebImage', '~> 3.7.6'
pod 'AFNetworking', '~> 3.1.0'

end

